name: 'puppet-lint'
author: 'puppet-lint'
description: 'Executes puppet-lint scan and output SARIF result.'
inputs:
  output-file:
    description: 'Output file'
    required: false
    default: 'result.sarif'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.output-file }}

branding:
 color: gray-dark
 icon: shield
